import os

SETTINGS_MAIN_SECTION = "MainWindow"

SETTINGS_GEOMETRY = "geometry"
SETTINGS_WINDOW_STATE = "window_state"
SETTINGS_SHOW_STATUSBAR = "show_statusbar"

SETTINGS_AUTOREFRESH_ENABLED = "autorefresh_enabled"
SETTINGS_AUTOREFRESH_TIMEOUT = "autorefresh_timeout"
SETTINGS_AUTOREFRESH_TIMEOUT_DEFAULT = 5000  # in miliseconds

SETTINGS_AUTOSAVE_IMAGE_ENABLED = "autosave_image_enabled"
SETTINGS_AUTOSAVE_IMAGE_ENABLED_DEFAULT = False

SETTINGS_IMAGE_FORMAT = "image_format"

SETTINGS_USE_CUSTOM_JAVA = "use_custom_java"
SETTINGS_USE_CUSTOM_JAVA_DEFAULT = True
SETTINGS_CUSTOM_JAVA_PATH = "custom_java"

SETTINGS_USE_CUSTOM_PLANTUML = "use_custom_plantuml"
SETTINGS_USE_CUSTOM_PLANTUML_DEFAULT = True
SETTINGS_CUSTOM_PLANTUML_PATH = "custom_plantuml"

SETTINGS_USE_CUSTOM_GRAPHIZ = "use_custom_graphiz"
SETTINGS_USE_CUSTOM_GRAPHIZ_DEFAULT = True
SETTINGS_CUSTOM_GRAPHVIZ_PATH = "custom_graphviz"

SETTINGS_ASSISTANT_XML_PATH = "assistant_xml"

SETTINGS_USE_CACHE = "use_cache"
SETTINGS_USE_CACHE_DEFAULT = True
SETTINGS_USE_CUSTOM_CACHE = "use_custom_cache"
SETTINGS_USE_CUSTOM_CACHE_DEFAULT = False
SETTINGS_CUSTOM_CACHE_PATH = "custom_cache"
SETTINGS_CACHE_MAX_SIZE = "cache_max_size"
SETTINGS_CACHE_MAX_SIZE_DEFAULT = 50 * 1024 * 1024  # in bytes

SETTINGS_RECENT_DOCUMENTS_SECTION = "RecentDocuments"

SETTINGS_PREFERENCES_SECTION = "Preferences"

SETTINGS_EDITOR_SECTION = "Editor"

SETTINGS_EDITOR_FONT = "font"
SETTINGS_EDITOR_INDENT = "indent"
SETTINGS_EDITOR_INDENT_DEFAULT = True
SETTINGS_EDITOR_INDENT_SIZE = "indent_size"
SETTINGS_EDITOR_INDENT_SIZE_DEFAULT = 4
SETTINGS_EDITOR_INDENT_WITH_SPACE = "indent_with_space"
SETTINGS_EDITOR_INDENT_WITH_SPACE_DEFAULT = True
SETTINGS_EDITOR_REFRESH_ON_SAVE = "refresh_on_save"
SETTINGS_EDITOR_REFRESH_ON_SAVE_DEFAULT = False

SETTINGS_EDITOR_LAST_DIR = "last_work_dir"
SETTINGS_EDITOR_LAST_DIR_DEFAULT = ""

TIMEOUT_SCALE = 1000

if os.name == 'nt':
    SETTINGS_CUSTOM_JAVA_PATH_DEFAULT = "C:/Program Files (x86)/Java/jre7/bin/java.exe"
    SETTINGS_CUSTOM_PLANTUML_PATH_DEFAULT = "C:/plantuml.jar"
    SETTINGS_CUSTOM_GRAPHVIZ_PATH_DEFAULT = "C:/Program Files (x86)/Graphviz 2.28/dot.exe"
else:
    SETTINGS_CUSTOM_JAVA_PATH_DEFAULT = "/usr/bin/java"
    SETTINGS_CUSTOM_PLANTUML_PATH_DEFAULT = "/usr/bin/plantuml"
    SETTINGS_CUSTOM_GRAPHVIZ_PATH_DEFAULT = "/usr/bin/dot"
